server:
  port: 30000
spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#    alicloud:
#      oss:
#        endpoint: oss-cn-shenzhen.aliyuncs.com
#        bucket: gulimall-zzwang-2020-
#      access-key: LTAI4G2mhfNHP-2020-GHZzPvpDsTX
#      secret-key: md6at7ArJVcPP6-2020-Ps6woTtKd1dpqtmD

